### PR TITLE
Handling pages with no jquery, removing highlights, waiting for page load

### LINKED ISSUE #14: Add a wait for page to be finished loading before auto-scroll to first diff
See the new example here:

https://python.datasciencebook.ca/diff350/index.html

When I first go to a "diff'd" page, it tries to autoscroll to the first diff. But the page hasn't finished loading yet, so it gets stuck somewhere in the middle.

If I revisit the page again later, it works fine (because my browser has cached the whole page)

@briank-git I suspect we need to add an explicit wait until the page is done loading before the autoscroll happens.

(fun fact: I didn't change anything in the book *except* for the version control chapter. So all the diffs that are highlighted in classification1,2 etc are unintended changes that were caught! :D )

### LINKED ISSUE #15: Add check for jQuery and insert?
I noticed here:

https://github.com/trevorcampbell/website_diff/blob/fe6710ae6c0cd079bbbf444c8c4bb7754b6b7afb/website_diff/page.py#L79

we just insert the `js` and `css` for `website_diff`. But the `website_diff` javascript uses jQuery, so that has to be loaded too doesn't it?

We should test if this fails for websites that don't use jQuery, and if it does, add a check to see if the website already loads jQuery and if not load it.

### LINKED ISSUE #17: Remove selected diff highlight colouring?
Since we've moved now to "scroll to next diff offscreen", maybe we can get rid of the CSS darker highlighting for the selected diff.

### LINKED ISSUE #20: Bug in crawler?
See the GH actions run here: https://github.com/joelostblom/viz-oer/actions/runs/10729466334/job/29756120813#step:9:179

I've asked @joelostblom to provide the old/new websites that caused that error, and will report back here once I figure out what the underlying issue is.

### PR DESCRIPTION
**Pull request by trevorcampbell**
- Closes #14 
- Closes #15   --- but I'm not totally happy with this solution (it might end up conflicting with an existing version of jquery...)
- Closes #17 
- Closes #20 

Re #15 : @briank-git do you think we can reimplement `website_diff.js` without using jQuery? Just with base javascript, to avoid having to deal with dependencies? Or maybe you have a better idea how to handle dependencies

It would also be good if we solved #21 here

I think my solution for #14 , #17 , and #20 should be fine already

### CODE REVIEW

**Comment by briank-git** [comment]
Thanks @trevorcampbell for putting in the fixes. 

The fixes for #17 and #20 look good.

For #15, I think adding the following to the start of website_diff.js as you did in commit [f60a603](https://github.com/trevorcampbell/website_diff/pull/18/commits/f60a603f34ecf13c29633f273dd95c7cb6203cf2) is sufficient because it will check if jQuery was already loaded before loading jQuery:

```
if (typeof jQuery == 'undefined') {
  document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>');
}
```

Also I think [3da2763](https://github.com/trevorcampbell/website_diff/pull/18/commits/3da2763617e2fb81176bf39bafe901cee7e998e0) is redundant as the above snippet will load jQuery already.

But while testing above with a page that did not load jQuery natively, I found the page doesn't wait for jQuery to fully load before running the next function which used jQuery causing an error to be thrown about $ being undefined.

So instead of using `$(window).on("load, function() ...` on line 8 in website_diff.js, I found

```
document.onreadystatechange = function () {
  if (document.readyState == "complete") {
    // Function calls for scrolling to first diff and next diff
  }
}
```

allows for jQuery to fully load and should also cover issue #14.

If you think this makes sense then I can put my changes to the fixes for #15 and #14 in new commits to your branch.

**Comment by trevorcampbell** [comment]
@briank-git if you've thoroughly tested your idea and it works on large sites with and without jquery, then I'm happy with your proposal

**Comment by trevorcampbell** [comment]
One question: is the if statement in your proposed code snippet always guaranteed to trigger when a page loads (and is fully done loading)?

**Comment by briank-git** [comment]
@trevorcampbell From the documentation, it looks like document.readyState is "complete" right before the "load" event is fired (which I believe is when `$(window).on("load", function() ...` would run). https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState#complete

To avoid the if statement, a better option could be to use

```
window.addEventListener('load', (event) => {
  // Function calls for scrolling to first diff and next diff
});
```

**Comment by trevorcampbell** [comment]
That looks better to me (again, assuming you've tested it on one of our larger sites and it solves the scroll-before-load issue)

**Comment by briank-git** [comment]
I tested my changes and they are working fine. Feel free to comment or merge if ok.

**Pull request merged**
